# Dockerfile located in ./frontend/Dockerfile

# Stage 1: Build the application
FROM node:16-alpine as builder

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm

RUN pnpm install

COPY . .

ENV NODE_OPTIONS=--max-old-space-size=4096

RUN pnpm run build

# Add this line to list the contents of /app to debug
RUN ls -la /app

# Stage 2: Setup the runtime environment
FROM node:16-alpine

WORKDIR /app

# Copy over the built app and node_modules from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Expose the port your app runs on
EXPOSE 3000

# Command to run your app
CMD ["node", "build/index.js"]
